apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: dev-gitea
  labels:
    app: gitea
    component: database
type: Opaque
data:
  # username = gitea -> Z2l0ZWE=
  POSTGRES_USER: Z2l0ZWE=
  # password = gitea -> Z2l0ZWE=
  POSTGRES_PASSWORD: Z2l0ZWE=
