apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: dev-gitea
  labels:
    app: gitea
    component: database
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
